lua/vscode/theme.lua

This PR fixes the adding of new keys for diagnostics on newer Neovim 0.6.x. Fix #19

Add support to new diagnostic keys in Neovim

---

lua/vscode/colors.lua
lua/vscode/theme.lua

Update the LSP reference color according to the VSCode Dark+ reference
**Before**
**After**
**Reference**

feat: update LSP reference color

---

lua/vscode/colors.lua

When you have transparency set on your terminal, it gets rid of its transparency without this
allows for creating a global variable g:vscode_transparent to make background transparent

Add transparency

---

lua/vscode/theme.lua

The colors were wrong compared to https://vscode.dev/github/Microsoft/vscode. This is how they were:
The correct colors are on the screenshot here along with the color info: https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-dark-theme-colors-to-the-menu
For example, functions are yellow in code, but pink in the completion. They were linked, but this was incorrect.
I formatted using your settings file, but I must have a different version of stylua as it has changed a few things. Please feel free to change anything you want, and check I have not made any mistakes! Thanks.

Correct CmpItemKind colors

---

lua/vscode/theme.lua

Check the vscode_style once and save the result to the local variable. This changes make code more efficient and more readable.

refactor: check vscode_style one time only

---

extra/Xresources/vscode-dark
extra/Xresources/vscode-light

Add .Xresources config extra for X11 terminal emulators and other programs that can read these values.
https://wiki.archlinux.org/title/X_resources
Example with `htop` open in `st` terminal emulator:

feat: add Xresources config extra

---

lua/vscode/theme.lua

The colors for xml are not matching with vscode ones

fix(xml): fix xml colorscheme

---

lua/vscode/colors.lua
lua/vscode/theme.lua

**Dark theme**
**Light theme**
**Dark theme**
**Light theme**
**Dark theme**
**Light theme*
*

fix: fix indent-blankline.nvim color

---

README.md
extra/zathura/vscode-dark
extra/zathura/vscode-light

Color scheme extra for zathura document viewer (https://pwmt.org/projects/zathura/).

feat: add zathura document viewer color scheme extra

---

lua/vscode/theme.lua

I tried to make it look the same as VSCode as much as possible, but there is some limitation. The selected option's text should be a little bit brighter than the other options.

feat: update nvim-cmp highlight

---

README.md
extra/galaxyline/galaxyline.lua
lua/lualine/themes/vscode.lua
lua/vscode/colors.lua
lua/vscode/init.lua
lua/vscode/theme.lua
lua/vscode/utils.lua

Instead of using a separate variable to set the dark or light variants, we can use the default vim variable to set it.
Everything works as expected, even the function to change the theme on the fly.
```
:lua require('vscode').change_style("light")
:lua require('vscode').change_style("dark")
```

feat: using default vim variable to set dark or light variants

---

lua/vscode/theme.lua

This PR fixes https://github.com/Mofiqul/vscode.nvim/issues/37

fix: correct markdown inline code highlight

---

lua/vscode/theme.lua

This PR fixed the inline-code highlight color for the latest markdown parser
see the detail in  https://github.com/Mofiqul/vscode.nvim/pull/65#issuecomment-1168493944

fix: correct markdown_inline highlight color

---

lua/vscode/theme.lua

Highlight groups for [glepnir/dashboard-nvim](https://github.com/glepnir/dashboard-nvim) seem to be `cleared` by default: ensure values are set to match colorscheme.
| Dark | Light |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/36192863/178829217-51884d44-5db3-41eb-8ae2-ebb08aa81722.png) | ![image](https://user-images.githubusercontent.com/36192863/178829012-be18b5d4-8d71-4fbe-842e-a5172ee4bbaa.png) |

feat: add support for glepnir/dashboard-nvim

---

lua/vscode/init.lua

Also test for boolean values of backwards compatible configs on top of
the already tested integer values.

fix: Change vim.g.transparency check to vim.g.transparent

---

lua/vscode/theme.lua

| Aspect | Before | After |  
| -- | -- | -- |  
| COC.nvim menu | ![image](https://user-images.githubusercontent.com/23183656/182816386-cdcac8ec-2f97-4f20-b344-27d00d139a03.png) | ![image](https://user-images.githubusercontent.com/23183656/182816042-5d641915-4cd5-496b-a18f-9807c96bbd52.png)|
| Built-in menu | ![image](https://user-images.githubusercontent.com/23183656/182816589-2c686b97-6601-4baa-a24c-1f72d01cb268.png) | ![image](https://user-images.githubusercontent.com/23183656/182816758-8898c20a-033a-4369-8b1a-d2b9739cd951.png) |

feat(theme/light/coc,pmenu): add highlight

---

README.md

Forgot to add documentation for supported plugin: f1a3e73779d866fd50629ca98cb46b5be8bc3162

docs: add Dashboard to supported plugins

---

lua/vscode/theme.lua

I think that the highlight group `IndentBlanklineCurrentContext` should either be removed in order to use the plugins default settings, or should be changed to use an underline that matches the current context color set by #50.
This PR currently does the latter and preserves `IndentBlanklineCurrentContext` but sets `underline = true` and switches `guifg` with `guisp` for `vscContextCurrent`.
With `indent_blankline.setup({ show_current_context_start = true })`, vscode.nvim sets a foreground color for `IndentBlanlineContextStart`, resulting in treesitter highlights being overridden with `colors.vscContextCurrent`.
Using tokyonight as a comparison: 
`IndentBlanklineCurrentContext` isn't set at all, implying that the default settings from indent-blankline.nvim are used.

fix: set underline for indent-blankline ContextStart

---

lua/vscode/init.lua

When changing styles, printout shouldn't be forced on the user.
I'm bothered by it because I prefer to default this colorscheme with just
```lua
require("vscode").change_style("dark")
```
and that printout pops up every time I start Neovim.
Why do I set colorscheme like this?
I find it natural for colorscheme to set `vim.o.background = "dark"`, rather than the user and that's precisely what `change_style` does for me.

chore: remove unneeded printout

---

extra/WindowsTerminal/settings.json

Add a dark theme for the [Windows Terminal](https://github.com/microsoft/terminal) based on the [Alacritty config](https://github.com/Mofiqul/vscode.nvim/blob/5e23f929ebc60e99d5aae31db40d4cd892833732/extra/alacritty/alacritty.yml). 
Made this for my Windows setup, thought that it may be helpful.

Add Windows Terminal dark theme

---

README.md
colors/vscode.lua
colors/vscode.vim
lua/vscode/config.lua
lua/vscode/init.lua

When loading the plugin from a plugin manager the themes setup function would apply both configuration and the theme itself. This doesn't seem to be the case for many other popular colorschemes where only default/user configuration is applied on setup allowing the user to choose when to enable the colorscheme via `colorscheme {theme}` or `require('theme').load(style)`.
While applying these changes there were a few other things I modified.
- Allow style to be set from setup table and fallback to `vim.o.background`.
- Replace functionally for `vscode.change_style` to `vscode.load`.
Basically simplifies the plugins api.
- Rename colorscheme entrypoint file `colors/vscode.vim` to lua.
This doesn't change anything but appeals to be dislike of vimscript.
Much older versions of neovim might not …

refactor: handling config and theme initialization

---

lua/vscode/init.lua
lua/vscode/theme.lua

fix a error throws when color_overrides not set in user custom config.
the error msg I got as follows:
`
Error detected while processing /home/hewenjin/project/my/config/nvim/plugin/options.vim[45]../home/hewenjin/.local/share/nvim/site/pack/packer/start/vscode.nvim/colors/vscode.lua:
E5113: Error while calling lua chunk: vim/shared.lua:0: after the second argument: expected table, got nil
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
vim/shared.lua: in function 'tbl_extend'
.../site/pack/packer/start/vscode.nvim/lua/vscode/theme.lua:6: in function 'set_highlights'
...m/site/pack/packer/start/vscode.nvim/lua/vscode/init.lua:24: in function 'load'
...vim/site/pack/packer/start/vscode.nvim/colors/vscode.lua:2: in main chunk
`

fix: error when color_overrides not set

---

lua/vscode/theme.lua

This adds the [coc.nvim](https://github.com/neoclide/coc.nvim) highlight groups which are used for highlighting the symbol at the current cursor position.
The colors are the same as LSP reference highlight colors: [dark](https://github.com/Mofiqul/vscode.nvim/pull/23), [light](https://github.com/Mofiqul/vscode.nvim/pull/47).
**Dark:**
**Light:**

feat: highlight coc symbol under cursor

---

lua/vscode/config.lua
lua/vscode/init.lua
lua/vscode/theme.lua

Fixes #122
It seems that the config module: `config.setup` was not being initialized without explicitly calling the setup function, which broke vimscript config that is applied via global variables.

fix: global opts due to config not being initialized

---

README.md

According to bufferline doc: https://github.com/akinsho/bufferline.nvim/blob/01b20685000e704214e58d5d8cd0851c1657efee/doc/bufferline.txt#L71 The close command should be lowercase `bdelete %d`
Getting error when using uppercase:

docs: update README - bufferline close command

---

README.md
extra/foot/vscode-dark
extra/foot/vscode-light

I've added both vscode-dark and vscode-light colorschemes for [foot terminal](https://codeberg.org/dnkl/foot) and also updated the readme to reflect the same.

Added colorscheme for foot terminal

---

lua/lualine/themes/vscode.lua

This fixes #89 where the transparency is not respected in lualine.
Rather than setting `colors.bg and colors.bg2` to `NONE` I've used a ternary condition to set the color accordingly. This is because overriding `colors.bg and colors.bg2` to `NONE` initially will also set the foreground colors of modes to be `NONE` as well wherever they are set to `colors.bg or colors.bg2` which makes the text unreadable. 
I've tested this version and the colors look good and readable to me in both light and dark modes. Please mention if any changes are required. Thank you.

fix: Lualine does not respect transparency (#89)

---

lua/vscode/theme.lua

This fixes the weird background fill in Bufferline when transparency is set. In transparent mode Bufferline with it's background transparent makes more sense than having a strong grey bar.

fix: Bufferline background not transparent

---

lua/vscode/theme.lua

I noticed that the diffs are not highlighted in [vim-gitgutter](https://github.com/airblade/vim-gitgutter)'s preview window:
This preview window is parsed by the [relatively recent Treesitter's diff parser](https://github.com/nvim-treesitter/nvim-treesitter/pull/3684), which adds two new highlight groups.
To fix the issue, this PR links the new highlight groups to `DiffAdd` and `DiffDelete`:

feat: support highlight groups of Treesitter's diff parser

---

lua/vscode/theme.lua

After neovim 0.9 update all parentheses with this theme were yellow.
I fix it

Fix parentheses highlight

---

extra/zathura/vscode-dark

Boolean is not a valid color value type in zathura config files. Replacing it with the correct hex value.

fix: zathura color theme extra bg color invalid value

---

lua/vscode/colors.lua
lua/vscode/theme.lua

As a user of the theme, I want `color_overrides`, which I have passed during the setup, to have effect on `get_colors` elsewhere. Currently, they only have effect during the initialization of the theme.
Add deep table merge into `get_colors`.
Tested locally by importing colors in different other places of my setup.

fix: make `get_colors` return wrt to `color_overrides`

---

lua/vscode/theme.lua

When debugging with nvim-dap, it uses the [debugPC](https://github.com/mfussenegger/nvim-dap/blob/9adbfdca13afbe646d09a8d7a86d5d031fb9c5a5/lua/dap.lua#L254) highlight to emphasize which line the debugger is at.
before (nvim):
after (nvim):
dark+ (vscode):

Show current line when debugging

---

extra/i3/vscode-dark
extra/zathura/vscode-dark

I have made a couple visual tweaks in the i3wm and zathura dark theme extras since I submitted them:
- Made the zathura statusbar text use the white instead of the darker gray color - more legible and matching nsxiv image viewer and lf file manager status bar colors for example.
- Made i3wm status bar to have more visible unfocused display active workspace number indicator - full bg. gray highlight. And a more visible i3 mode indicator - purple instead of cyan, which previously was (too) same as the active workspace. Example with bar on 3 displays:

i3wm and zathura theme changes

---

lua/vscode/theme.lua

This PR aims to improve support for [barbar.nvim](https://github.com/romgrk/barbar.nvim). There has always been this little spill after the last tab which bothered me. This PR fixes that by changing the background color of the tabline to match it.
| Before | After |
| --- | --- |
| ![Screenshot from 2024-02-23 21-40-24](https://github.com/Mofiqul/vscode.nvim/assets/16181067/8b19ce23-d592-4f10-8b11-1d122553039b)  |![Screenshot from 2024-02-23 21-41-52](https://github.com/Mofiqul/vscode.nvim/assets/16181067/d3fca749-1447-4033-9935-948577e50ec3) |
Full Neovim looks like this:
On light mode:

fix: Improve barbar support by changing tabline background color

---

extra/alacritty/alacritty.yml

I tried to use the alacritty theme and found that it was outdated (alacritty complained about the background opacity option), the colors didn't match, the cursor made the text under it invisible, and it included things like fonts and window sizes, which don't pertain to this repo (IMO).
Alacritty now also supports importing additional configuration files, so I documented how to do that:
```yml
```

Update alacritty theme and leave only colors in it

---

lua/vscode/theme.lua

Upgrading to 0.10 for a bit showed me that `vscode.nvim` is missing a couple of highlights.
(notice the [dropbar.nvim](https://github.com/Bekaboo/dropbar.nvim) colored black because it's missing `WinBar` and `WinBarNC`, and the floating popup colored black because it's missing `NormalFloat`)
I'm certain there are more to come, but this is what I've found for now.

Add some highlights used by Neovim 0.10

---

extra/Xresources/vscode-dark
extra/Xresources/vscode-light

The nsxiv image viewer appearance can be configured through .Xresources. The extras change sets the more noticeable green and red colors for the selected file and the marked file indicator in the image thumbnails view.

feat(extra): .Xresources add nsxiv window highlights

---

lua/vscode/theme.lua

this is a one liner because on the top of the function, you declared as `c` not `colors`

fix: on theme.lua still use global colors instead of c

---

README.md

I noticed that when the project "vscode theme" loads using `require('vscode').load()`, it affects the colors of devicons (there's a chance that the icons fail to color every time it's opened). I'm not sure why this issue occurs, but I found that using `vim.cmd.colorscheme "vscode"` to load doesn't encounter the problem. Although not everyone uses devicon, I think it's worth mentioning in the README to alert users who use both devicon and the vscode theme.

Fix devicon color issue by loading theme with vim.cmd

---

after/queries/jsx/highlights.scm

Unfortunately, this required creating a Treesitter query as I couldn't find an easy way of having `@type` overwrite `@tag`, and even if I did, it wouldn't be accurate anyway
the query is partially copied from the nvim-treesitter repository with a few differences
- in relevant queries, `@tag` has been replaced with `@type` to be consistent with VSCodes colouration 
- `(#lua-match? "^[A-Z]")` has been replaced with `(#lua-match? "[A-Z]")` as VScode will highlight a JSX tag as a type if a capital letter is present anywhere within the tag name, not just at the beginning
- if a tag has `-` in its name, it will be highlighted as a `@type` like VSCode (this is what the `(#lua-match? "%-")` queries are for)
resolves part of #189

correctly highlight JSX/TSX components

---

extra/zathura/vscode-dark
extra/zathura/vscode-light

Recently zathura switched to defining text selection block transparency via the RGBA color value of the selection block, so this fix makes it visible what's behind the selection blocks.
I also made the link numbers red to make them slightly more noticeable (even though it's not ideal as they are always behind the highlighted selection blocks).

fix(extra): zathura theme text selection not being transparent

---

lua/vscode/config.lua
lua/vscode/init.lua
lua/vscode/utils.lua

The plugin should set the vim terminal colors. There are many benefits, such as:
- The terminal colors match the reset of neovim
- Neovim guis, such as [neovide](https://github.com/neovide/neovide), wont be stuck with default term colors
- When changing style terminal will update accordingly
Plugins such as [tokyonight.nvim](https://github.com/folke/tokyonight.nvim/blob/c91aef1125e052c9d862e68389e4185ec56f6cde/lua/tokyonight/util.lua#L120-L147) already do this, to great effect. Potentially the colors shouldn't be based on highlight groups, as is the case right now, but rather based directly on the gui term colors.

Support terminal colors

---

lua/vscode/theme.lua

After:
Before: notice that `QuickFixLine` is defined to Neovim 0.10 defaults.

Add highlight for QuickFixLine 'bold = true'

---

README.md
extra/fzf/vscode-dark
extra/fzf/vscode-light

Styled according to how fzf looks with vscode.nvim colors applied according to a snippet from the fzf-lua plugin docs: https://github.com/ibhagwan/fzf-lua/blob/86b77a661ff38bf08b1ceb5a6c3c257285a42a4d/doc/fzf-lua.txt#L810C1-L810C26

feat(extra): fzf color scheme

---

lua/vscode/theme.lua

These changes reduce the shifting of colors that happens as one navigates hunks with the cursor on a `NeogitStatus` buffer. It reduces accessibility a tiny bit (by not showing a cursor line highlight inside hunks) but makes the theme look less broken and makes it easier to follow what's going on.

Improve Neogit highlights

---

extra/alacritty/vscode-dark.toml
extra/alacritty/vscode-light.toml

Some of the colors in the alacritty themes were either from the wrong variant, or just the wrong color. This brings alacritty in-line with the kitty theme.

fix(alacritty): colors

---

lua/vscode/colors.lua

I feel like [this change](https://github.com/Mofiqul/vscode.nvim/commit/396dd65c14275e54e388d49d8a08871448880407#diff-932a387ba84163d24624ebd618f36c5477edcad607e5385b76a263f679a459faL28) makes `cursorline` and `colorcolumn` too staggering and that it shouldn't be a default.
@Mofiqul, do you mind clarifying why it was made this way?
Without this PR:
With this PR:

revert cursorline/colorcolumn breaking change

---

README.md
lua/vscode/theme.lua

Add support for [`Snacks.indent`](https://github.com/folke/snacks.nvim/blob/main/docs/indent.md) (same highlighting as Indent Blankline).

feat: add support for Snacks.indent
