Mofiqul/vscode.nvim

extra/galaxyline/galaxyline.lua
lua/vscode/theme.lua

barbar.nvim is the plugin for displaying buffers https://github.com/romgrk/barbar.nvim
**Before**
**After**
**VSCode Reference**

Add support for barbar.nvim

---

README.md

Add transparency to README

---

lua/vscode/theme.lua

https://github.com/Mofiqul/vscode.nvim/pull/30#issuecomment-1007544268

Fix treesitter markdown header marker and list colors

---

lua/lualine/themes/vscode.lua

colors.gray was not set -> instead use colors.bg to match the colors like in the README screenshots

Bugfix: lualine colors: inactive section

---

lua/vscode/colors.lua
lua/vscode/theme.lua

This PR fixes this issue #45 
**Result**

fix: fix LSP highlight for light theme

---

README.md

- grammar
- code formatting
- remove trailing whitespace

docs: format README.md

---

lua/lualine/themes/vscode.lua

Make lualine look cooler.
NORMAL:
VISUAL:
REPLACE:
INSERT:
COMMAND:

change lualine mode colors, add command mode colors

---

lua/vscode/colors.lua

This PR solve https://github.com/Mofiqul/vscode.nvim/issues/55
**Result**

feat: update search highlight color

---

lua/vscode/theme.lua
lua/vscode/utils.lua

Use `vim.api.nvim_set_hl` as suggested in #57.
Since the current stable version 0.7.2 supports the `nvim_set_hl` function, it
can be used in this colorscheme package.

Use nvim_set_hl in theme.lua

---

lua/vscode/colors.lua
lua/vscode/theme.lua

Add color highlights for NvimTree git files

---

lua/vscode/colors.lua
lua/vscode/theme.lua

See commit messages.
`lua/lualine/themes/vscode.lua` has the same problem imo, but for some reason still seems to work as expected so I did not change it. Please have a look at that.

fix: #78 Cannot switch style to light / dark

---

README.md

As flagged by https://github.com/Mofiqul/vscode.nvim/issues/102
Reference: https://github.com/akinsho/bufferline.nvim/blob/877e778afd2dbbe52b9847d9ea473a29a0c3646d/doc/bufferline.txt#L710

Update README.md: fix outdated bufferline config to up-to-date expected table

---

lua/vscode/theme.lua

Recent update to dashboard.nvim changed a few highlight groups.

fix: dashboard.nvim highlight

---

lua/lualine/themes/vscode.lua

- Sort lualine groups alphabetically
- Add inactive color since reusing colors weren't visually distinct
- Add terminal mode table that just reuses insert mode colors

Improve lualine theme

---

README.md
lua/vscode/theme.lua

This PR adds support for [NeogitOrg/neogit](https://github.com/NeogitOrg/neogit/). Modification suggestions welcome, of course.
| Theme | Before (No hunks highlighted) | Before (Top hunk highlighted) | After (No hunks selected) | After (First/Top hunk selected) |
|-------|-------------------------------|--------------------------------|---------------------------|---------------------------------|
| Dark  | ![](https://github.com/Mofiqul/vscode.nvim/assets/16181067/012006f6-05c6-44ec-888d-3e828262d5f4) | ![](https://github.com/Mofiqul/vscode.nvim/assets/16181067/539f7bcf-e82f-4ef6-a9fb-373cc86c03bf) | ![](https://github.com/Mofiqul/vscode.nvim/assets/16181067/47079864-beef-4256-8ca5-d29180c8f38d) | ![](https://github.com/Mofiqul/vscode.nvim/assets/16181067/3cd7ed2a-96ab-47db-8cde-2df5cba81 …

feat: Add support for NeogitOrg/neogit

---

extra/alacritty/vscode-dark.toml
extra/alacritty/vscode-light.toml

Alacritty moved from yaml to toml, so I suggest actualizing alacritty config

actualize alacritty config

---

extra/WindowsTerminal/settings.json
extra/Xresources/vscode-dark
extra/alacritty/alacritty.yml
extra/alacritty/vscode-dark.toml
extra/alacritty/vscode-light.toml
extra/foot/vscode-dark
extra/i3/vscode-dark
extra/kitty/vscode-dark.conf
extra/wezterm/vscode-dark.toml
extra/zathura/vscode-dark
extra/zathura/vscode-light
lua/vscode/colors.lua

using a colour inspector and `Developer: Inspect editor Tokens and Scopes` apparently the background colour is supposed to be `#1F1F1F`
please ignore #196 I fucked up lmao :^)

correct dark background colour (`#1E1E1E` to `#1F1F1F`)

---

README.md
lua/vscode/theme.lua

Add support for plugin Trouble

---

lua/vscode/theme.lua

This adds basic Neotree colors.

Add neotree colors

---

README.md
extra/linux-console/vscode-dark
extra/linux-console/vscode-linux

Having those VS Code colors outside of the graphical (X11/Wayland) session.

feat(extra): linux console color scheme

---

README.md

Added in #198, took me a while to find why colors changed

doc: add terminal_colors to README

---

README.md
extra/ghostty/vscode-dark
extra/ghostty/vscode-light

This PR adds the theme config file for the [ghostty terminal emulator](https://ghostty.org/).

feat: add ghostty color scheme

---

extra/zellij/vscode-dark.kdl
extra/zellij/vscode-light.kdl

Added a theme for [Zellij](https://zellij.dev)

feat(extra): add zellij color scheme

---

lua/vscode/theme.lua

Should solve the missing highlights problem in https://github.com/Mofiqul/vscode.nvim/issues/152 .

Replaced v2 highlights with v3 highlights

---

README.md
lua/vscode/theme.lua

Add support for [which-key](https://github.com/folke/which-key.nvim).

feat: add which-key support
